//
//  DetailViewController.swift
//  Ski Maintenance Information
//
//  Created by Jeewoo Chung on 12/1/20.
//  Copyright © 2020 Jeewoo Chung. All rights reserved.
//

import UIKit

class DetailViewController: UIViewController {

    @IBOutlet var imageView: UIImageView! {
        didSet {
            imageView.image = UIImage(named: step)
        }
    }
    @IBOutlet var titleLabel: UILabel! {
        didSet {
            titleLabel.text = step
        }
    }
    @IBOutlet var textView: UITextView! {
        didSet {
            textView.text = data[step]
        }
    }
    
    let data = [
        "Waxing":"1. Secure the skis or snowboard to your bench. Place your skis or board flat and base side up and securely supported at the tips and tails They should be clamped or braced so they won’t move while you work on them. Pull up the ski brakes and use a thick rubber band stretched between the brake arms and over the heel piece to keep them out of the way. \n\n2. Begin dripping wax onto the skis or snowboard. Hold the hot iron upright with the point or one corner facing down. Press the wax to the iron, moving it around on the hot surface. This will start melting the wax, dripping a small stream onto the ski or snowboard. You don’t need full coverage here, you’ll spread the wax over the entire base in the next step. \n\n3. Use the iron to spread the wax over the entire ski or snowboard. Put the iron to the ski base and move it down the ski to melt the wax you’ve deposited on the base. The goal here is to spread the wax out evenly so it penetrates the entire base. Keep the iron moving at all times; usually a speed of about 1 - 2 inches per second will prevent damage to the base by overheating. Too hot to touch with your hand is too hot! \n\n4. Let the wax cool completely. It’s best to leave your skis or snowboard at room temperature until the bases feel completely cool to the touch, usually about 30 minutes. If in doubt, wait a little longer. \n\n5. Once cool, you can move on to scraping and brushing the skis or snowboard.",
        "Sharpening Edges":"1. After attaching your vise to a long flat surface, restrain the ski brake.  The easiest way is to use a strong rubber band and loop it around one arm of the brake, over the heel housing, and over the other arm. \n\n2. Place the ski base up onto the vice. \n\n3. Using whatever base file guide you have lock it onto the ski with a metal file and draw down the edge in a smooth stroke.  Repeat this as least four times and then do the same for the other base edge.  If an area has significant burring you can work on that one area even more, but remember to address the burr first and the entire edge afterwards. \n\n4. Still addressing the base edge of the ski, switch from a metal file to a diamond stone and repeat.  Using the guide draw the guide down the edge another four to five times.  This should remove the striation marks left from the file and firmly hone the angle set by the file. \n\n5. Ideally you will also have a ceramic stone, and at this point you repeat step 4 with the ceramic stone.  The ceramic stone will provide a perfect finishing polish and leave the edge bevel set perfectly. \n\n6. Using the vertical hold on your vise place the ski on one side.  Using whatever side edge guide you have, with a metal file, lock in onto the ski  and draw the guide down the ski from tip to tail.  Repeat this as least four times and then do the same for the other base edge.  If an area has significant burring you can work on that one area even more, but remember to address the burr first and the entire edge afterwards. \n\n7. Repeat steps 4-5 with the side edge guide and then flip the ski to address the other side edge. When doing edge work remember that 4 to five passes per file or stone are purely recommendations.  The more you work on edges the easier it will be to recognize when an edge is properly set.  Also, while metal files are incredibly useful they are not necessary every time you work on your edges.  If you continue to re-hone the edges diamond and ceramic stones are the most valuable tools you can have, as they will keep an edge sharp without having to continually remove edge material.  Not only does this make edge maintenance easier each time but makes the edge last longer.  Above anything else remember patience is your best friend when it comes to edge work, take your time and learn to read what the edges tell you.",
        "Installing Bindings":"Mounting Ski Bindings.... It's pretty easy when you do it everyday and you have the proper tools to do so.  Mounting your bindings properly is very important.  If you've noticed when you pick your skis up after an adjust or mount; the tech or shop kid always goes over the bindings with you and shows you that everything is in working order.  We don't do this because it's fun and we like to hear ourselves talk we do this because your safety is important. \n\nWhen we drill into a ski we don't do it free hand and we don't do it with a paper template either.  We buy jigs from the manufacturer at a couple hundred bucks a piece. Proper drilling is the reason we use these things we call jigs, you don't want to miss-drill and you don't want to drill through the ski (that would suck).  We also want to make sure that we're drilling the toe and heel piece in the right spots for you specific boot. When you are adjusting the jig to the length of the ski boot, you want that marking to line up with the mid sole marking on the binding jig. \n\n\n1. Once you have those lined up and the jig position locked in place, it's time to place the jig on the ski, but where?  On the ski there is a similar marking like on the ski boot or on most freeride skis there is a reference. If you are using the ski all-mountain or don't have a preference mount at zero. Zero means factory recommended or not mounted forward or back.  Some skiers have a preference as to where they like to be mounted and it  can and usually does differ from ski to ski.  When in doubt, ask! \n\n2. So after all that explaining it's finally time to drill your skis!  There are a variety of bits you can use, but the most commonly used bits are the 4.1 x 9.5 used for skis with metal in the core, the 3.5 x 9.5 is good most wood or composite core skis to prevent stripping and the 3.5 x 7 is used for all junior skis and skis that are thinner then an adult ski. \n\n3. Once your holes are drilled, make sure you get any of the excess/loose wood out of the holes so your ski bases don't dimple when you put the screws in, this is a common mistake.  After that put a little bit of wood glue in each hole then your good to start mounting your bindings on your new skis.",
        "Choosing the Right Skis":"1. Choose the type of ski based on your preferred terrain: Your choices are all-mountain skis, all-mountain wide skis, powder skis and backcountry skis. The type of skis you choose will be based on the type of skiing you plan to do. \n\n2. Find your preferred ski length: As a general rule, choose a ski length that comes up to between your chin and the top of your head. Use our size chart for a more precise fit. \n\n3. Confirm your ski dimensions support the type of skiing you like to do: Skinnier skis are better for carving turns on groomed runs, while wider skis provide better flotation in deep snow. (The type of ski you choose will inform these dimensions.) \n\n4. Understand how camber and rocker affect ski performance: If you stick to groomed slopes, skis with standard alpine camber or perhaps some tip rocker will be right for you. If you prefer deep snow, look for tip and tail rocker or full rocker for better flotation. \n\n5. Decide if you want integrated bindings or want to buy bindings separately: Skis with integrated bindings installed are convenient and ensure good performance. However, many intermediate and advanced skiers prefer skis without integrated bindings so they can pick bindings that meet their specific needs.",
        "Tweaking Bindings":"Once a technician has adjusted your bindings to fit your boot, the next step is to adjust the DIN. On both the toe and heelpiece, the technician will rotate the screw to your DIN setting. DIN settings are visible on top of the binding toe and heelpiece. \n\nDIN is an acronym for Deutsches Institut für Normung, which has been adopted internationally by the ski industry. It refers to the force needed for a binding to release a boot in order to reduce the potential for or the severity of injury.\n\nRemember those embarrassing questions the ski technician asked when you brought in your gear (weight, height, skier type)? Here’s where they come into play.\n\nThe DIN uses your stats to arrive at a number to guide the binding release. On your binding, that number is set on the toe and heelpiece.\n\nHow do the DIN settings work? The lower the setting or number, the less force it takes for your binding to release. This is especially important when your body is going one direction and the skis another. Bindings that release can prevent torqueing knees in the wrong direction.\n\nFor DIN, beginners and children use lower settings. Hence, the bindings will release more easily.\n\nFor adult beginning or intermediate skiers, the number may be bumped higher to accommodate the increased weight, somewhere between 3-10. Otherwise, their weight alone would cause them to slide out of their bindings on every turn.\n\nAdvanced skiers will use even higher DIN settings, which take more force to release. Skiers who like speed and jumping off terrain park features might need to go with a higher setting of 6-14.\n\nRacers, professional skiers and big mountains skiers use the highest settings, around 8-18. The higher the setting, the greater the risk and the more you must rely on your skills to bail you out of a twisting fall.\n\nSometimes skiers up their DIN to prevent pre-releasing or slipping out of the bindings before a big fall. But, cranking up the DIN can result in a torn ACL or broken leg. Other skiers view having higher DINs as a bragging right.\n\nThis should not be viewed that way though. Unnecessarily high DIN settings only invite injury.\n\nTo find your DIN, consult a DIN chart or use a DIN calculator. The charts give approximate DIN ranges, while the calculators pinpoint a number. Add your weight, height, age, skier type and boot sole length to arrive at your DIN.",
        "Storing Skis":"Many beginners just put their ski equipment laying around the house until the end of the season. Not only is this messy, while transporting, the equipments are exposed to possible damage. Use the following guide to properly store and transport your ski equipment before and after riding.\n\n1. Get a single (or double) ski bag. They only cost around $50 and they are essential to protecting your expensive skis. These bags will not only make your skis and poles convenient to carry, they will protect the skis, your car, and the floors of your house.\n\n2. Wrap your skis using ski straps. They are long strands of foam with velcro that will hold your skis together. Skis are held together at the bindings, and they can sometimes come apart during transport. This can be risky for the skis and everyone else around you, so secure your skis.\n\n3. Lastly, get a boot bag. These massive, waterproof backpacks will not only store your heavy ski boots, but there is usually enough room to store everything else including your helmet, goggles, gloves, and whatever else.\n\n\nIf you followed all the steps, your gear should now be protected and all you will have to carry is your boot bag and your ski bag. No more searching around the house last minute for your gloves or your goggles.",
        "Carrying Skis":"The easiest way to carry skis for any distance, is to put the skis on your shoulder and hold them with one hand. To do this, the first thing you need to do is put the skis together.\n\nWith the skis standing vertically, hold each ski by the toe housing on the binding. With one ski slightly higher than the other, put the skis base to base, and slide the higher ski down along the other ski until the brakes lock together. Having the skis like this stops them from coming apart so easily, and makes them a lot easier to carry.\n\nThen being careful not to hit anyone or anything with the skis, put the skis on your preferred shoulder, with the area just in front of the bindings resting on your shoulder. When you do this the the ski that was higher when putting the skis together, needs to be the bottom ski that rests on your shoulder. This will stop the top ski from being able to slide forwards, and make the skis much easier to carry. To hold the skis in position, push down gently towards the ski tips with the hand on the same side as the shoulder the skis are resting on. Now hold your poles in the other hand, and you are ready to carry your skis wherever you need to go.\n\nWhen carrying skis like this please be careful not to hit anyone or anything with the skis. Do not swing the skis around while you walk, and be aware of the back of the skis when you go around corners. With the added difficulty of walking in ski boots, and through snow, extra care needs to be taken while carrying skis.\n\nIf you come to a slow moving, crowded area, like a lift queue. Carefully take the skis off of your shoulder without hitting anyone or anything, and stand them vertically next to you, holding them with one hand around the area just above the bindings. Holding the skis like this, takes the weight off of your shoulder, and is a lot safer for the people around you. When you move forwards, simply pick the skis up and put them back down with the one hand as if the skis were a large walking stick.\n\nYou can also pick the skis up and carry them while they are vertical by holding the toe housing on the ski that is underneath when you slide the skis together.",
        "After-Ride Checklist":"1. DRY OFF SKIS AT THE END OF EACH DAY:\n\nSimply using a towel to wipe off the water from melted snow goes a long way to preventing rust on a ski edges or corrosion in the bindings. There’s really no excuse for skipping this 30-second chore that requires absolutely no technical expertise.\n\n\n2. SMOOTH OUT BURRS AT THE END OF EACH DAY:\n\nIf you run your thumb down each steel ski edge, you may feel some tiny nicks or minor scrapes from rock damage. Use a pocket stone to touch up any spots with imperfections.",
        "Storing Skis (Long-Term)":"Storing your skis in a temperature controlled environment is imperative to keeping them in good condition for next season. This means storing them in a place where the temperature and humidity are consistent.\n\nYou should never store your skis in an attic or garage, the temperature and humidity levels are subject to change frequently and can cause your skis to rust.\n\nKeeping your skis in a Ski Bag for the off season is a good option. Just make sure that your skis are dry before putting them away, and always leave the bag unzipped to allow moisture to escape. This lets rust-causing moisture escape the bag, rather than stick to your skis.\n\nIf you are looking for an out-of-the-way storage spot for your skis, upright in the corner of a closet and underneath your bed are two great solutions."
    ]
    
    var step: String!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Do any additional setup after loading the view.
    }
    

}
